[package]
name = "tcpserver"
version = "0.1.0"
authors = ["yi lu <luyikk@126.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/luyikk/tcp_server"
documentation = "https://docs.rs/tcpserver"
description = "rust tcp server frame."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
log="0.4.11"
bytes = "0.5.6"
xbinary = "0.1.3"